sociagraph/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from sociagraph import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^key_information_extractor/', include('key_information_extractor.urls', namespace="key_information_extractor")),
    url(r'^sentiment_analyzer/', include('sentiment_analyzer.urls', namespace="sentiment_analyzer")),
    url(r'^admin/', include(admin.site.urls)),
]

theme_matcher/urls.py
from django.conf.urls import patterns, url

from theme_matcher import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^corpus/$', views.corpus, name='corpus'),
    url(r'^results/$', views.results, name='results'),
    url(r'^add_corpus/$', views.add_corpus, name='add_corpus'),
)

sociagraph/models.py
from django.db import models
	
class English_Dictionary(models.Model):
	word = models.TextField()
	associated_word = models.TextField()

class Part_of_Speech(models.Model):
	short_hand = models.CharField(max_length = 10)
	long_hand = models.CharField(max_length = 300)

class Classified_Corpus(models.Model):
	text = models.TextField()
	theme = models.TextField()

class Sentiment_Corpus(models.Model):
	text = models.TextField()
	emotion = models.TextField()

sociagraph/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()

sociagraph/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
	template_name = 'sociagraph/index.html'
	
	return render(request, template_name)

sociagraph/templates/includes/footer.html
{% load staticfiles %}

		<nav id="footer" class="navbar navbar-inverse navbar-fixed-bottom" >
			<div class="container-fluid">
				<span id="copyright">Sociagraph &copy; 2014</span>
				<span id="back-to-top"><a href="#">Back to Top</a></span>
			</div>
		</nav>
	</body>
	<script type="text/javascript" src="{% static 'sociagraph/jquery-1.11.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'sociagraph/bootstrap.js' %}"></script>
	<script type="text/javascript" src="{% static 'sociagraph/scripts.js' %}"></script>
</html>

sociagraph/templates/includes/header.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
	<head>
		<title>Sociagraph</title>
		<link rel="stylesheet" type="text/css" href="{% static 'sociagraph/bootstrap.min.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'sociagraph/style.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'sociagraph/responsive.css' %}" />
	</head>

	<body>
		<nav id="sociagraph-header" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
						<span class="sr-only"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>

					<a class="navbar-brand header-menu-item" href="{% url 'index' %}">Sociagraph</a>
				</div>

				<div class="collapse navbar-collapse" id="navbar-collapse">
					<ul class="nav navbar-nav">
						<li class="active"><span class="sr-only"></span></li>
						{% if user.is_active and user.is_staff %}
							<li class="dropdown" id="menu-nav">
								<a href="#" class="dropdown-toggle header-menu-item" data-toggle="dropdown">
									{% if application_name == "admin" %}
										<span class="active-menu">{% firstof user.get_short_name user.get_username %}</span>
										<span class="caret active-menu"></span>
									{% else %}
										<span>{% firstof user.get_short_name user.get_username %}</span> <span class="caret"></span>
									{% endif %}
								</a>
								<ul class="dropdown-menu" role="menu">
									<li><a href="{% url 'admin:index' %}"> Admin Home</a></li>
									{% if user.has_usable_password %}
										<li><a href="{% url 'admin:password_change' %}"> Change Password</a></li>
									{% endif %}
									<li><a href="{% url 'admin:logout' %}"> Logout</a></li>
								</ul>
							</li>
						{% else %}
							<li class="dropdown" id="menu-nav">
								<a href="{% url 'admin:index' %}">Login</a>
							</li>
						{% endif %}
						<li class="dropdown" id="key-information-extractor-nav">
							<a href="#" class="dropdown-toggle header-menu-item" data-toggle="dropdown">
								{% if application_name == "key-information-extractor" %}
									<span class="active-menu">Key Information Extractor</span>
									<span class="caret active-menu"></span>
								{% else %}
									<span>Key Information Extractor</span> <span class="caret"></span>
								{% endif %}
							</a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{% url 'key_information_extractor:index' %}"><span class="glyphicon glyphicon-filter"></span> Extract Key Information</a></li>
								<li class="divider"></li>
									<li><a href="{% url 'key_information_extractor:corpus' %}"><span class="glyphicon glyphicon-th-list"></span> Theme-classified Data</a></li>
									<li><a href="{% url 'key_information_extractor:add_corpus' %}"><span class="glyphicon glyphicon-plus"></span> Add Themed Data</a></li>
							</ul>
						</li>
						<li class="dropdown" id="sentiment-analyzer-nav">
							<a href="#" class="dropdown-toggle header-menu-item" data-toggle="dropdown">
								{% if application_name == "sentiment-analyzer" %}
									<span class="active-menu">Sentiment Analyzer</span>
									<span class="caret active-menu"></span>
								{% else %}
									<span>Sentiment Analyzer</span> <span class="caret"></span>
								{% endif %}
							</a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{% url 'sentiment_analyzer:index' %}"><span class="glyphicon glyphicon-search"></span> Analyze Sentiment</a></li>
								<li class="divider"></li>
									<li><a href="{% url 'sentiment_analyzer:corpus' %}"><span class="glyphicon glyphicon-th-list"></span> Sentiment-labeled data</a></li>
									<li><a href="{% url 'sentiment_analyzer:add_corpus' %}"><span class="glyphicon glyphicon-plus"></span> Add Sentiment Data</a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</nav>

sociagraph/templates/includes/notification.html
{% if notification_type == 'success' %}
	<div class="notification alert alert-success" role="alert">{{ notification_message }}</div>
{% elif notification_type == 'error' %}
	<div class="notification alert alert-danger" role="alert">{{ notification_message }}</div>
{% endif %}

sociagraph/templates/includes/pagination.html
<ul class="pagination">
    {% if items.paginator.num_pages > 1 %}
        <li><a href="?page={{ 1 }}">First</a></li>
        {% if items.has_previous %}
            <li><a href="?page={{ items.previous_page_number }}">&laquo;</a></li>
        {% endif %}

        <li class="active">
            <span class="current">
                {{ items.number }} of {{ items.paginator.num_pages }}
            </span>
        </li>

        {% if items.has_next %}
            <li><a href="?page={{ items.next_page_number }}">&raquo;</a></li>
        {% endif %}
        <li><a href="?page={{ items.paginator.num_pages }}">Last</a></li>
    {% endif %}
</ul>