key_information_extractor/urls.py
from django.conf.urls import patterns, url

from key_information_extractor import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^corpus/$', views.corpus, name='corpus'),
    url(r'^results/$', views.results, name='results'),
    url(r'^add_corpus/$', views.add_corpus, name='add_corpus'),
)

sociagraph/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from sociagraph import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^key_information_extractor/', include('key_information_extractor.urls', namespace="key_information_extractor")),
    url(r'^sentiment_analyzer/', include('sentiment_analyzer.urls', namespace="sentiment_analyzer")),
    url(r'^admin/', include(admin.site.urls)),
]

key_information_extractor/models.py
from django.db import models

# Create your models here.

key_information_extractor/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from sociagraph.models import Classified_Corpus
from django.db.models import Q

from sociagraph.utils import *


def index(request):
	application_name = "key-information-extractor"
	template_name = 'key_information_extractor/index.html'

	return render(request, template_name, {
		'application_name': application_name,
		})


def corpus(request):
	application_name = "key-information-extractor"
	template_name = 'key_information_extractor/corpus.html'

	# Get the corpora from the database
	classified_corpus = Classified_Corpus.objects.all()

	# Count all corpora in the database
	total_corpora_count = classified_corpus.count()

	# Setup pagination
	paginator = Paginator(classified_corpus, 10)

	# Get the requested page
	page = request.GET.get('page')

	try:
		corpora = paginator.page(page)
	except PageNotAnInteger:
		corpora = paginator.page(1)
	except EmptyPage:
		corpora = paginator.page(paginator.num_pages)

	new_classified_corpus = []

	# Convert themes from string to list
	for corpus in corpora:
		new_classified_corpus.append((corpus.text, corpus.theme.split(',')))

	return render(request, template_name, {
		'application_name': application_name,
		'classified_corpus': new_classified_corpus,
		'items': corpora,
		'total_corpora_count': total_corpora_count,
		})


def results(request):
	application_name = "key-information-extractor"
	template_name = 'key_information_extractor/results.html'

	# Get the input
	themes = request.POST.get('theme')
	original_text = request.POST.get('text')
	
	# Clean the themes
	themes = remove_non_letters(themes)
	themes = remove_extra_whitespaces(themes)
	theme_list = tokenize(themes)

	# ==== Output variables ====
	tokens = tokenize(original_text)
	original_text_length = count_words(original_text)
	vocabulary_size = get_vocabulary_count(original_text)
	bag_of_words = sort_dictionary_by_key(get_bag_of_words(original_text))

	pos_tags = get_pos_tags(original_text)
	pos_tags = get_pos_tag_values(pos_tags)

	theme_classification_results = {}
	theme_classification_statistics = {}
	theme_definitions = {}
	corpora_statistics = {}
	# ==========================

	for theme in theme_list:
		theme_definitions[theme] = get_word_definitions(theme)

		labeled_text = {}

		not_theme = 'not_' + theme

		# Get text with matching theme from database
		labeled_corpora = Classified_Corpus.objects.filter(theme__contains=theme).values('text').order_by('?')
		
		# Count the corpora in the database
		labeled_corpora_count = labeled_corpora.count()

		if labeled_corpora_count >= 3:
			# Get text not matching the theme from database
			opposite_labeled_corpora = Classified_Corpus.objects.filter(~Q(theme__contains=theme)).values('text').order_by('?')[:labeled_corpora.count()]

			# Assign each result to given theme
			labeled_text[theme] = assign_theme(labeled_corpora, theme)

			# Assign each result to given theme
			labeled_text[not_theme] = assign_theme(opposite_labeled_corpora, not_theme)

			# Combine opposing themes
			combined_labeled_text = labeled_text[theme] + labeled_text[not_theme]
			
			# Shuffle the combined text with labels
			shuffle_set(combined_labeled_text)
			
			# Get the vocabulary of the combined labels
			feature_set_words = get_feature_set_words(combined_labeled_text)

			# Check if the words in a paragraph is in feature set words
			feature_sets = get_theme_corpus_feature_sets(combined_labeled_text, feature_set_words, theme)

			set_size = len(feature_sets)/2
			test_set = feature_sets[:set_size]
			train_set = feature_sets[set_size:]

			svm_classifier = create_svm_classifier()
			svm_classifier = train_classifier(svm_classifier, train_set)

			test_set_features = []
			test_set_correct_classifications = []
			classification_scores = {}

			# Get the test features and labels for metrics
			for features, labels in test_set:
				test_set_features.append(features)
				test_set_correct_classifications.append(labels)

			test_set_reclassification = svm_classifier.classify_many(test_set_features)
			classification_scores = get_classification_scores(test_set_correct_classifications, test_set_reclassification, [theme, not_theme])

			classified_items = {}
			keywords = []

			for sentence in paragraph_to_sentences(original_text):
				classification_test = get_features(sentence, feature_set_words, theme)

				# Get each theme classification per sentence
				classified_items[sentence] = svm_classifier.classify(classification_test)

				# word_count = len(tokenize(sentence))

				# for counter in range(1, 3):
				# 	for ngram in get_ngrams(sentence, counter):
				# 		if is_possible_keyword(ngram):
				# 			classification_test = get_features(" ".join(ngram), feature_set_words, theme)
				# 			classified_items[" ".join(ngram)] = svm_classifier.classify(classification_test)

			theme_classification_results[theme] = classified_items
			theme_classification_statistics[theme] = classification_scores
			corpora_statistics[theme] = sort_dictionary_by_key({ 'Corpora Total': labeled_corpora_count, 'Test Set Count': labeled_corpora_count/2, 'Train Set Count': labeled_corpora_count/2 })
			notification_type = 'success'
			notification_message = 'Successfully extracted key information'
		else:
			# Output if there is not data
			theme_classification_results[theme] = None
			theme_classification_statistics[theme] = None
			corpora_statistics[theme] = None
			notification_type = 'error'
			notification_message = 'Failed to extract all key information. Some themes are not in the database.'

	return render(request, template_name, {
		'application_name': application_name,
		'notification_type': notification_type,
		'notification_message': notification_message,
		'theme_definitions': theme_definitions,
		'original_text': original_text,
		'vocabulary_size': vocabulary_size,
		'original_text_length': original_text_length,
		'tokens': tokens,
		'bag_of_words': bag_of_words,
		'pos_tags': pos_tags,
		'theme_classification_results': theme_classification_results,
		'theme_classification_statistics': theme_classification_statistics,
		'corpora_statistics': corpora_statistics,
		})


def add_corpus(request):
	application_name = "key-information-extractor"
	template_name = 'key_information_extractor/add_corpus.html'

	return_values = {}
	return_values['application_name'] = application_name

	if request.POST:
		text = remove_extra_whitespaces(request.POST.get('text', False))
		theme = remove_spaces(request.POST.get('theme', False)).lower()

		if text != "" or theme != "":
			Classified_Corpus(text=text, theme=theme).save()

			return_values['notification_type'] = 'success'
			return_values['notification_message'] = 'Successfully added a theme-classified data.'
		else:
			return_values['notification_type'] = 'error'
			return_values['notification_message'] = 'Failed to add theme-classified data.'

	return render(request, template_name, return_values)

key_information_extractor/templates/key_information_extractor/add_corpus.html
{% load staticfiles %}
{% include 'includes/header.html' %}
<link rel="stylesheet" type="text/css" href="{% static 'key_information_extractor/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'key_information_extractor/add_corpus.css' %}" />

<div id="container" class="container-fluid">
	<h3 class="alert alert-success">Add Theme-classified Data</h3>
	{% include 'includes/notification.html' %}
	<div id="corpus-adder">
		<form id="corpus-adder-form" action="{% url 'key_information_extractor:add_corpus' %}" method="post" role="form">
		{% csrf_token %}
			<div class="form-group">
				<label for="text">Text</label>
				<textarea name="text" id="text" class="form-control" rows="9" cols="40" title="Type/Place the text that contains the concepts that you will provide." placeholder="Enter text" required></textarea>
			</div>
			<div class="form-group">
				<label for="theme">Themes <span class="glyphicon glyphicon-question-sign" title="Themes are the concepts expressed in the text."></span></label>
				<input type="text" name="theme" id="theme" class="form-control" title="Type the concepts that are expressed in the text." placeholder="theme,another_theme" required />
			</div>
			<div class="text-center"><input type="submit" class="btn btn-success" value="Add Theme-classified Data" /></div>
		</form>
	</div>
</div>

{% include 'includes/footer.html' %}

key_information_extractor/templates/key_information_extractor/corpus.html
{% load staticfiles %}
{% include 'includes/header.html' %}
<link rel="stylesheet" type="text/css" href="{% static 'key_information_extractor/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'key_information_extractor/corpus.css' %}" />

<div id="container" class="container-fluid">
	<h3 class="alert alert-success">List of Theme-classified Data</h3>
	<div class="text-center">{% include 'includes/pagination.html' %}</div>
	<h4 class="text-left">Total theme-classified data: {{ total_corpora_count }} classified texts</h4>
	<br />
	<table class="table table-hover table-condensed">
		<tr>
			<td class="table-header">Text</td>
			<td class="table-header">Themes <span class="glyphicon glyphicon-question-sign" title="Themes are the concepts expressed in the text."></span></td>					
		</tr>
		{% for text, themes in classified_corpus %}
		<tr>
			<td>{{ text }}</td>
			<td>
				<ul>
					{% for theme in themes %}
						<li>{{ theme }}</li>
					{% endfor %}
				</ul>
			</td>					
		</tr>
		{% endfor %}
	</table>
</div>

{% include 'includes/footer.html' %}

key_information_extractor/templates/key_information_extractor/index.html
{% load staticfiles %}
{% include 'includes/header.html' %}
<link rel="stylesheet" type="text/css" href="{% static 'key_information_extractor/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'key_information_extractor/index.css' %}" />

<div id="container" class="container-fluid">
	<h3 class="alert alert-success">Key Information Extractor</h3>
	<p>
		The key information extractor classifies information in the text based on the themes provided. 
	</p>
	<p>
		<strong>Note:</strong> The themes that can be used are limited to the themes in Sociagraph database. See <a href="{% url 'key_information_extractor:corpus' %}">list of theme-classified data</a> to see the available themes.
	</p>
	<br />
	<form id="theme-matcher-form" action="{% url 'key_information_extractor:results' %}" method="post" role="form">
	{% csrf_token %}
		<div class="form-group">
			<label for="theme">Themes <span class="glyphicon glyphicon-question-sign" title="Themes are the concepts expressed in the text."></label>
			<input type="text" name="theme" id="theme" class="form-control" title="Type the concepts that you want to extract from the text." placeholder="theme1,another_theme, ..." value="agriculture"/>
		</div>
		<div class="form-group">
			<label for="text">Text</label>
			<textarea name="text" id="text" class="form-control" rows="9" cols="40" title="Type/Place the text where the concepts will be extracted." placeholder="Enter text" required>Many of the trainings he  attended  in the last  two years  were   on   organic  agriculture, climate  change  and even hydrophonics .  to name  a few are as  follows;    Trainer on Training (TOT )on Organic farming (requested by Albay DTI), Trainer on Training (TOT) on Climate Change, Trainer on Training (TOT) on Organic farming and Organic fertilizers, Training on Vermicomposting, Training on Organic Swine and Poultry, Training on Hydrophonics KSK (Kaisa sa Kasaganaan): vegetables, producing high value commercial crops (December to April)</textarea>
		</div>
		<div class="text-center"><input type="submit" class="btn btn-success" value="Extract Information" required /></div>
	</form>
</div>

{% include 'includes/footer.html' %}

key_information_extractor/templates/key_information_extractor/results.html
{% load staticfiles %}
{% include 'includes/header.html' %}
<link rel="stylesheet" type="text/css" href="{% static 'key_information_extractor/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'key_information_extractor/results.css' %}" />

<div id="container" class="container-fluid">
	<h3 class="alert alert-success">Key Information Extraction Results</h3>
	{% include 'includes/notification.html' %}
	<ul id="menu-tabs" class="nav nav-tabs" role="tablist">
		<li class="active"><a href="#classification-results" role="tab" data-toggle="tab">Classification Results</a></li>
		<li><a href="#classification-statistics" role="tab" data-toggle="tab">Classification Statistics</a></li>
		<li><a href="#inputs" role="tab" data-toggle="tab">Inputs</a></li>
		<li><a href="#tokens" role="tab" data-toggle="tab">Tokens <span class="glyphicon glyphicon-question-sign" title="Tokens are the separated words in the text."></span></a></li>
		<li><a href="#bag-of-words" role="tab" data-toggle="tab">Word Frequency</a></li>
		<li><a href="#pos-tags" role="tab" data-toggle="tab">Part of Speech Tags</a></li>
	</ul>

	<div class="tab-content">
		<div id="classification-results" class="tab-pane fade in active">
			<div class="panel panel-default">
				<div class="panel-body">
					<table class="table table-hover table-condensed">
						<tr>
							<td class="table-header">Sentence</td>
							<td class="table-header">Label</td>
						</tr>
						{% for theme, per_sentence in theme_classification_results.items %}
							{% for sentence, label in per_sentence.items %}
								<tr>
									<td>{{ sentence }}</td>
									<td>{{ label }}</td>
								</tr>
							{% endfor %}
						{% endfor %}
					</table>
				</div>
			</div>
		</div>

		<div id="classification-statistics" class="tab-pane fade">
			{% for theme, scores in theme_classification_statistics.items %}
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title"><strong>{{ theme }}</strong></h3>
					</div>
					<div class="panel-body">
						{% if scores == None %}
							No data.
						{% else %}
							<h4 class="text-left"><strong>Evaluation Metrics</strong></h4>
							<table class="table table-hover table-condensed">
								{% for category, score in scores.items %}
									<tr>
										<td>{{ category.title }}</td>
										<td>{{ score }}</td>
									</tr>
								{% endfor %}
							</table>
							<h4 class="text-left"><strong>Corpora Information</strong></h4>
							<table class="table table-hover table-condensed">	
								{% for corpora_theme, statistics in corpora_statistics.items %}
									{% if corpora_theme == theme %}
										{% for index, value in statistics %}
											<tr>
												<td>{{ index }}</td>
												<td>{{ value }}</td>
											</tr>
										{% endfor %}
									{% endif %}
								{% endfor %}
							</table>
						{% endif %}
					</div>
				</div>
			{% endfor %}
		</div>
		<div id="inputs" class="tab-pane fade in">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><strong>Input Statistics</strong></h3>
				</div>
				<div class="panel-body">
					<p>Vocabulary Size: {{ vocabulary_size }}</p>
					<p>Number of Words: {{ original_text_length }}</p>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><strong>Theme Data</strong></h3>
				</div>
				<div class="panel-body">
					{% for theme, definitions in theme_definitions.items %}
						<strong>{{ theme }}</strong>
						{% if definitions != None %}
							{% for definition in definitions %}
								<li>{{ definition }}</li>
							{% endfor %}
						{% else %}
							<br />
							No data.
							<br />
						{% endif %}
						<br />
					{% endfor %}
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><strong>Text</strong></h3>
				</div>
				<div class="panel-body">
					<p class="text-justify">{{ original_text }}</p>
				</div>
			</div>
		</div>

		<div id="tokens" class="tab-pane fade">
			<div class="panel panel-default">
				<div class="panel-body">
					<table class="table table-hover table-condensed">
						{% for token in tokens %}
							<tr>
								<td>{{ token }}</td>
							</tr>
						{% endfor %}
					</table>
				</div>
			</div>
		</div>

		<div id="bag-of-words" class="tab-pane fade">
			<div class="panel panel-default">
				<div class="panel-body">
					<table class="table table-hover table-condensed">
						<tr>
							<td class="table-header">Word</td>
							<td class="table-header">Frequency</td>
						</tr>
						{% for word, frequency in bag_of_words %}
						<tr>
							<td>{{ word }}</td>
							<td>{{ frequency }}</td>
						</tr>
						{% endfor %}
					</table>
				</div>
			</div>
		</div>

		<div id="pos-tags" class="tab-pane fade">
			<div class="panel panel-default">
				<div class="panel-body">
					<table class="table table-hover table-condensed">
						<tr>
							<td class="table-header">Word</td>
							<td class="table-header">Part of Speech</td>
						</tr>
						{% for word, tag, pos in pos_tags %}
						<tr>
							<td>{{ word }}</td>
							<td>{{ pos }}</td>
						</tr>
						{% endfor %}
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

{% include 'includes/footer.html' %}