sentiment_analyzer/urls.py
from django.conf.urls import patterns, url

from sentiment_analyzer import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^results/$', views.results, name='results'),
    url(r'^corpus/$', views.corpus, name='corpus'),
    url(r'^add_corpus/$', views.add_corpus, name='add_corpus'),
    url(r'^upload_corpus/$', views.upload_corpus, name='upload_corpus'),
)

sociagraph/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from sociagraph import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^key_information_extractor/', include('key_information_extractor.urls', namespace="key_information_extractor")),
    url(r'^sentiment_analyzer/', include('sentiment_analyzer.urls', namespace="sentiment_analyzer")),
    url(r'^admin/', include(admin.site.urls)),
]

sentiment_analyzer/views.py
from django.shortcuts import render
from django.http import HttpResponse
from sociagraph.models import Sentiment_Corpus
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from sociagraph.utils import *
from sociagraph.forms import UploadFileForm

def index(request):
	application_name = "sentiment-analyzer"
	template_name = 'sentiment_analyzer/index.html'

	return render(request, template_name, {
		'application_name': application_name,
		})


def corpus(request):
	application_name = "sentiment-analyzer"
	template_name = 'sentiment_analyzer/corpus.html'

	# Get the corpora from the database
	sentiment_corpus = Sentiment_Corpus.objects.all()

	# Count the total corpora in the database
	total_corpora_count = sentiment_corpus.count()
	
	# Setup pagination
	paginator = Paginator(sentiment_corpus, 10)

	# Get requested page
	page = request.GET.get('page')

	try:
		corpora = paginator.page(page)
	except PageNotAnInteger:
		corpora = paginator.page(1)
	except EmptyPage:
		corpora = paginator.page(paginator.num_pages)

	new_classified_corpus = []

	for corpus in corpora:
		new_classified_corpus.append((corpus.text, corpus.emotion.split(',')))

	return render(request, template_name, {
		'application_name': application_name,
		'total_corpora_count': total_corpora_count,
		'sentiment_corpus': new_classified_corpus,
		'items': corpora,
		})

def results(request):
	application_name = "sentiment-analyzer"
	template_name = 'sentiment_analyzer/results.html'

	original_text = request.POST.get('text')

	sentiments = ['happy', 'sad', 'angry', 'fearful', 'neutral']
	
	# Clean the text for processing
	filtered_text = remove_extra_whitespaces(original_text)

	# Process the tokens
	tokens = tokenize(original_text)

	# Get vocabulary size
	vocabulary_size = get_vocabulary_count(original_text)
	original_text_length = count_words(original_text)
	# Process the Bag of Words
	bag_of_words = sort_dictionary_by_key(get_bag_of_words(original_text))

	# Process POS Tagging
	pos_tags = get_pos_tags(original_text)
	pos_tags = get_pos_tag_values(pos_tags)

	# Get all text from database
	# labeled_corpora = Sentiment_Corpus.objects.all()
	labeled_corpora = Sentiment_Corpus.objects.all()

	# Count corpora in the database
	labeled_corpora_count = labeled_corpora.count()

	# ==== Output variables ====
	corpora_statistics = {}
	emotion_labeled_corpora = []
	overall_sentiment = ''
	# ==========================

	for corpus in labeled_corpora:
		emotion_labeled_corpora.append((unicode_to_string(remove_stopwords(corpus.text)), unicode_to_string(corpus.emotion)))

	shuffle_set(emotion_labeled_corpora)

	# Get the vocabulary
	feature_set_words = get_feature_set_words(emotion_labeled_corpora)

	# Check if the words in a paragraph is in feature set words
	feature_sets = get_sentiment_feature_sets(emotion_labeled_corpora, feature_set_words, sentiments)

	set_size = len(feature_sets)/2
	test_set = feature_sets[:set_size]
	train_set = feature_sets[set_size:]

	svm_classifier = create_svm_classifier()
	svm_classifier = train_classifier(svm_classifier, train_set)

	test_set_features = []
	test_set_correct_classifications = []

	# Get the test features and labels for metrics
	for features, labels in test_set:
		test_set_features.append(features)
		test_set_correct_classifications.append(labels)

	test_set_reclassification = svm_classifier.classify_many(test_set_features)
	sentiment_classification_statistics = get_classification_scores(test_set_correct_classifications, test_set_reclassification, sentiments)	

	classified_sentences = {}
	sentiment_frequency = { 'happy': 0, 'sad': 0, 'angry': 0, 'fearful': 0, 'neutral': 0 }

	for sentence in paragraph_to_sentences(original_text):
		classification_test = get_sentiment_features(sentence, feature_set_words, sentiments)

		# Get each theme classification per sentence
		classification = svm_classifier.classify(classification_test)
		classified_sentences[sentence] = classification
		sentiment_frequency.update({ classification: sentiment_frequency[classification]+1 })
	overall_sentiment = get_most_frequent_sentiment(sentiment_frequency)
	corpora_statistics = sort_dictionary_by_key({ 'Corpora Total': labeled_corpora_count, 'Test Set Count': labeled_corpora_count/2, 'Train Set Count': labeled_corpora_count /2})
	sentiment_frequency = sort_dictionary_by_value(sentiment_frequency)

	notification_type = 'success'
	notification_message = 'Successfully analyzed text sentiment.'

	return render(request, template_name, {
		'application_name': application_name,
		'notification_type': notification_type,
		'notification_message': notification_message,
		'original_text': original_text,
		'filtered_text': filtered_text,
		'vocabulary_size': vocabulary_size,
		'original_text_length': original_text_length,
		'corpora_statistics': corpora_statistics,
		'tokens': tokens,
		'pos_tags': pos_tags,
		'bag_of_words': bag_of_words,
		'sentiment_frequency': sentiment_frequency,
		'classified_sentences': classified_sentences,
		'overall_sentiment': overall_sentiment,
		'sentiment_classification_statistics': sentiment_classification_statistics,
		})

def add_corpus(request):
	application_name = "sentiment-analyzer"
	template_name = 'sentiment_analyzer/add_corpus.html'

	return_values = {}
	return_values['application_name'] = application_name

	if request.POST:
		text = remove_extra_whitespaces(request.POST.get('text', False))
		emotion = remove_spaces(request.POST.get('sentiment', False)).lower()

		if text != "" or emotion != "":
			Sentiment_Corpus(text=text, emotion=emotion).save()

			return_values['notification_type'] = 'success'
			return_values['notification_message'] = 'Successfully added a sentiment-labeled data.'
		else:
			return_values['notification_type'] = 'error'
			return_values['notification_message'] = 'Failed to add sentiment-labeled data.'

	return render(request, template_name, return_values)

def upload_corpus(request):
	return_values = {}
	filename = request.POST.get('corpus_file')
	if request.method == 'POST':
		form = UploadFileForm(request.POST, request.FILES)
		if form.is_valid():
			form = request.FILES['corpus_file']
	else:
		form = UploadFileForm()
	return_values['notification_type'] = 'error'
	return_values['notification_message'] = 'Failed to add sentiment-labeled data.'

	return render(request, 'admin/upload_message.html', {'form': filename})

sentiment_analyzer/templates/sentiment_analyzer/add_corpus.html
{% load staticfiles %}
{% include 'includes/header.html' %}
<link rel="stylesheet" type="text/css" href="{% static 'sentiment_analyzer/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'sentiment_analyzer/add_corpus.css' %}" />

<div id="container" class="container-fluid">
	<h3 class="alert alert-success">Add Sentiment Data</h3>
	{% include 'includes/notification.html' %}
	<div id="corpus-adder">
		<form id="corpus-adder-form" action="{% url 'sentiment_analyzer:add_corpus' %}" method="post" role="form">
		{% csrf_token %}
			<div class="form-group">
				<label for="text">Text</label>
				<textarea name="text" id="text" class="form-control" rows="9" cols="40" title="Type/Place the text that express the emotion that you will provide." placeholder="Enter text" required></textarea>
			</div>
			<div class="form-group">
				<label for="sentiment">Sentiment <span class="glyphicon glyphicon-question-sign" title="Sentiment is the emotion mostly expressed in the text."></span></label>
				<select name="sentiment" id="sentiment" class="form-control" title="Select the emotion mostly expressed in the text.">
					<option value="neutral">Neutral</option>
					<option value="happy">Happy</option>
					<option value="sad">Sad</option>
					<option value="angry">Angry</option>
					<option value="fearful">Fearful</option>
				</select>
			</div>
			<div class="text-center"><input type="submit" class="btn btn-success" value="Add Sentiment Data" /></div>
		</form>
	</div>
</div>

{% include 'includes/footer.html' %}

sentiment_analyzer/templates/sentiment_analyzer/corpus.html
{% load staticfiles %}
{% include 'includes/header.html' %}
<link rel="stylesheet" type="text/css" href="{% static 'sentiment_analyzer/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'sentiment_analyzer/corpus.css' %}" />

<div id="container" class="container-fluid">
	<h3 class="alert alert-success">List of Sentiment-labeled Data</h3>
	<div class="text-center">{% include 'includes/pagination.html' %}</div>
	<h4 class="text-left">Total sentiment-labeled data: {{ total_corpora_count }} classified texts</h4>
	<br />
	<table class="table table-hover table-condensed">
		<tr>
			<td class="table-header">Text</td>
			<td class="table-header">Sentiment <span class="glyphicon glyphicon-question-sign" title="Sentiment is the emotion mostly expressed in the text."></span></td>					
		</tr>
		{% for text, sentiments in sentiment_corpus %}
		<tr>
			<td>{{ text }}</td>
			<td>
				{% for sentiment in sentiments %}
					{{ sentiment }}
				{% endfor %}
			</td>					
		</tr>
		{% endfor %}
	</table>
</div>

{% include 'includes/footer.html' %}

sentiment_analyzer/templates/sentiment_analyzer/index.html
{% load staticfiles %}
{% include 'includes/header.html' %}
<link rel="stylesheet" type="text/css" href="{% static 'sentiment_analyzer/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'sentiment_analyzer/index.css' %}" />

<div id="container" class="container-fluid">
	<h3 class="alert alert-success">Sentiment Analyzer</h3>
	<p>
		The sentiment analyzer classifies information in the text using sentiments happy, sad, angry, fearful, neutral. 
	</p>
	<br />
	<form action="{% url 'sentiment_analyzer:results' %}" method="post" role="form">
	{% csrf_token %}
		<div class="form-group">
			<label for="text">Text</label>
			<textarea name="text" id="text" class="form-control" rows="8" cols="40" title="Type the text to determine the most expressed emotion." placeholder="Enter text" required>It is such as great day to do SP. There are many wonderful lessons that can be learned. This is a nice way to travel. Transportation in this area is scary. This is such an awful event.</textarea>
		</div>
		<div class="text-center"><input type="submit" class="btn btn-success" value="Analyze Sentiment" /></div>
	</form>
</div>

{% include 'includes/footer.html' %}

sentiment_analyzer/templates/sentiment_analyzer/results.html
{% load staticfiles %}
{% include 'includes/header.html' %}
<link rel="stylesheet" type="text/css" href="{% static 'sentiment_analyzer/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'sentiment_analyzer/results.css' %}" />

<div id="container" class="container-fluid">
	<h3 class="alert alert-success">Sentiment Analysis Results</h3>
	{% include 'includes/notification.html' %}
	<ul id="menu-tabs" class="nav nav-tabs" role="tablist">
		<li class="active"><a href="#classification-results" role="tab" data-toggle="tab">Classification Results</a></li>
		<li><a href="#classification-statistics" role="tab" data-toggle="tab">Classification Statistics</a></li>
		<li><a href="#inputs" role="tab" data-toggle="tab">Inputs</a></li>
		<li><a href="#tokens" role="tab" data-toggle="tab">Tokens <span class="glyphicon glyphicon-question-sign" title="Tokens are the separated words in the text."></span></a></li>
		<li><a href="#bag-of-words" role="tab" data-toggle="tab">Word Frequency</a></li>
		<li><a href="#pos-tags" role="tab" data-toggle="tab">Part of Speech Tags</a></li>
	</ul>

	<div class="tab-content">
		<div id="classification-results" class="tab-pane fade in active">
			<div class="panel panel-default">
				<div class="panel-body">
					<table class="table table-hover table-condensed">
						<tr>
							<td class="table-header">Sentence</td>
							<td class="table-header">Sentiment</td>
						</tr>
						{% for sentence, sentiment in classified_sentences.items %}
							<tr>
								<td>{{ sentence }}</td>
								<td>{{ sentiment }}</td>
							</tr>
						{% endfor %}
					</table>
				</div>
			</div>
		</div>

		<div id="classification-statistics" class="tab-pane fade">
			<div class="panel panel-default">
				<div class="panel-body">
					<h4 class="text-left"><strong>Sentiment Frequencies</strong></h4>
					<br />
					<h4 class="text-center"><b><i>Overall Sentiment: {{ overall_sentiment.upper }}</i></b></h4>
					<br />
					<table class="table table-hover table-condensed">
						<tr>
							<td class="table-header">Sentiment</td>
							<td class="table-header">Frequency</td>
						</tr>
						{% for sentiment, frequency in sentiment_frequency %}
							<tr>
								<td>{{ sentiment }}</td>
								<td>{{ frequency }}</td>
							</tr>
						{% endfor %}
					</table>

					<h4 class="text-left"><strong>Evaluation Metrics</strong></h4>
					<table class="table table-hover table-condensed">
						{% for category, score in sentiment_classification_statistics.items %}
							<tr>
								<td>{{ category.title }}</td>
								<td>{{ score }}</td>
							</tr>
						{% endfor %}
					</table>
					<h4 class="text-left"><strong>Corpora Information</strong></h4>	
					<table class="table table-hover table-condensed">	
						{% for index, value in corpora_statistics %}
							<tr>
								<td>{{ index }}</td>
								<td>{{ value }}</td>
							</tr>
						{% endfor %}
					</table>
				</div>
			</div>
		</div>
		<div id="inputs" class="tab-pane fade in">
			{{ test }}
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><strong>Input Statistics</strong></h3>
				</div>
				<div class="panel-body">
					<p>Vocabulary Size: {{ vocabulary_size }}</p>
					<p>Number of Words: {{ original_text_length }}</p>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><strong>Text</strong></h3>
				</div>
				<div class="panel-body">
					<p class="text-justify">{{ original_text }}</p>
				</div>
			</div>
		</div>

		<div id="tokens" class="tab-pane fade">
			<div class="panel panel-default">
				<div class="panel-body">
					<table class="table table-hover table-condensed">
						{% for token in tokens %}
						<tr>
							<td>{{ token }}</td>
						</tr>
						{% endfor %}
					</table>
				</div>
			</div>
		</div>

		<div id="bag-of-words" class="tab-pane fade">
			<div class="panel panel-default">
				<div class="panel-body">
					<table class="table table-hover table-condensed">
						<tr>
							<td class="table-header">Word</td>
							<td class="table-header">Frequency</td>
						</tr>
						{% for word, frequency in bag_of_words %}
						<tr>
							<td>{{ word }}</td>
							<td>{{ frequency }}</td>
						</tr>
						{% endfor %}
					</table>
				</div>
			</div>
		</div>

		<div id="pos-tags" class="tab-pane fade">
			<div class="panel panel-default">
				<div class="panel-body">
					<table class="table table-hover table-condensed">
						<tr>
							<td class="table-header">Word</td>
							<td class="table-header">Part of Speech</td>
						</tr>
						{% for word, tag, pos in pos_tags %}
							<tr>
								<td>{{ word }}</td>
								<td>{{ pos }}</td>
							</tr>
						{% endfor %}
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

{% include 'includes/footer.html' %}